### ISSUE TITLE
QoL: Code formatting config for better consistency?

### ISSUE THREAD

**Issue by ducktordanny** [p5quared/apple-music.nvim#21]
For easier contribution and better consistency, I'd suggest adding some type of formatting config, e.g. in my [configs](https://github.com/ducktordanny/.dotfiles/blob/master/config/nvim/.stylua.toml), I use [StyLua](https://github.com/JohnnyMorganz/StyLua) which only requires a `.stylua.toml` file with your preferences.

After this, you can use e.g. Mason or whatever to get the LSP for it and have any formatting plugin to apply the proper formatting (e.g. I use conform.nvim).

Any thoughts on this? I think it would be great to have something like this :)

(Edit: I wanted to post this in a discussion but clicked the button in the wrong tab... I'll leave it here now, hope it's fine)

**Comment by p5quared** [comment]
A little formatting definitely goes a long way. I think it's lower priority than some of the 'front-facing' stuff like #20 or #15 but worth implementing at some point.

Thanks for sharing your configs for reference, I'll take a look!
