### ISSUE TITLE
Autocmd for playlist cleanup after VimLeave evemt? (Enhancement)

### ISSUE THREAD

**Issue by Ren-B-7** [p5quared/apple-music.nvim#35]
This is an enhancement not a bug!  

Wouldnt an additional enhancement to the "work around" be to create an autocmd for running cleanup on VimLeave, photos included.
![CodeSnap_2024-11-21_at_23:43:01](https://github.com/user-attachments/assets/2ac4cfb3-036b-49a0-a958-c75bda5b3a18)

**Comment by p5quared** [comment]
Love this idea! :heart:

I'd be open to a PR and if not, I'm currently travelling but will 100% add this in the near future.
