### ISSUE TITLE
Help docs don't show up in Neovim

### ISSUE THREAD

**Issue by p5quared** [p5quared/apple-music.nvim#4]
Not sure why but I cannot find the documentation with `:help`

**Comment by ducktordanny** [comment]
`h apple-music.nvim` works fine for me.
<img width="191" alt="Screenshot 2024-07-20 at 10 52 06" src="https://github.com/user-attachments/assets/63760013-3cb3-4cc4-9722-3fe8b5ab679c">

**Comment by p5quared** [comment]
Oh phew, it must just be a _me_ issue! 😌
